README.md
I think this was a small typo?
=> Fix name of babel plugin in docs

package.json, tsconfig.json
The package was not emitting typings so consumers were seeing typescript errors when importing TailwindProvider.
=> Emit typings

README.md
Minor change to the last step of the quick start guide in the readme, which still contains an import from the depreciated <TailwindProvider />.
=> fix: update quick start docs for NativeWind

apps/website/docs/home.md
A quick typo fix for the link leading to [Parent state styles](https://www.nativewind.dev/core-concepts/states#styling-based-on-parent-state) page
=> Docs: Fix link to parent state styles

packages/nativewind/src/tailwind/native/line-height.ts
Using tailwindcssReactNative plugin in the tailwind.config.js with the VSCode plugin Tailwind CSS IntelliSense cause an error on starting.
The function leading receive a boolean instead of a string and and errors is throw with the call of value.endsWith.
I have just added a type check in the function.
=> fix tailwind intellisense error : endsWith is not a function

packages/nativewind/src/styled/use-tailwind.ts
When working with next.js ssr, `useSyncExternalStoreWithSelector` requires the `getServerSnapshot` argument, otherwise an [error](https://github.com/marklawlor/nativewind/discussions/141#discussioncomment-3315674) will be thrown.
=> fix `useSyncExternalStoreWithSelector` missing `getServerSnapshot` argument

apps/website/docs/quick-starts/nextjs.md
First of all, thanks a lot for this amazing work, we just started migrating our project to nativewind and everything is looking great so far.
However, we were running into problems using the `parent` variant on next as it was not doing anything. Fortunately requiring the plugin explicitly worked for us and I wanted to make it a bit clear in the docs.
I don't understand how tailwind's plugin system works, but looking at the config types and their docs, it seems that it doesn't accept strings.
=> chore(docs): add require in nextjs setup

apps/website/docs/quick-starts/expo.md
Added note about postcss-loader version as per our conversation here #218.
=> Point out postcss-loader version in Webpack warning

apps/website/docs/quick-starts/react-native-cli.md
This package is awesome. Kudos to you @marklawlor and all of the maintainers.
While I'm following the docs for react-native cli, I saw that there is a confusing class insertion outside a View component tag. I just want it to be clear by creating this PR.
Thanks in advance
=> chore(docs): fix confusing View component remove and add for rn-cli

.changeset/popular-onions-visit.md, packages/nativewind/src/babel/index.ts
Hi there, thanks for working on nativewind. Its a lot of fun to use!
I have been running into #67 for files without tailwind styles. I found that `safelist` has a default value of an empty array and therefore the default `babel-empty` class wasn't set.
https://github.com/marklawlor/nativewind/blob/9481eb58c368ac4c6d5760cb1897b542e7e17fd1/packages/nativewind/src/babel/index.ts#L138
The issue can be reproduced over here, run `yarn native ios -c`:
https://github.com/nandorojo/solito/tree/84ffea9675a86c9bbb2aad4c64b7454e49673dd7/example-monorepos/with-tailwind
The warning will be printed for `App.tsx` first.
Now,  I don't have any knowledge of the implementation of nativewind - and I may have ruined everything. Do let me know if there is anything to change.
=> Check for empty `safelist` array instead of undefined

apps/website/docs/quick-starts/create-react-native-app.md
Hi, thanks for creating this awesome project! I was trying out nativewind and found a little typo. 
In the create-react-native-app quickstart, instead of `tailwind.config.js`, `tailwind.config.ts` was written. I have fixed the typo in this pull request.
=> docs: fix typo in create-react-native quickstart

apps/website/docs/quick-starts/expo.md, apps/website/docs/quick-starts/ignite.md, apps/website/docs/quick-starts/react-native-cli.md
In the expo, react-native-cli and ignite quickstart, instead of tailwind.config.js, tailwind.config.ts was written. I have fixed the typos in this pull request.
=> docs: fix typos in quickstarts

apps/website/docs/guides/custom-components.mdx
hey @marklawlor I missed this one when passing style from parent to child so I think adding the notice above the code will make it more easier to note
=> add caution admonitions to make the warning / tip more easy to catch

package.json, packages/nativewind/types.d.ts, packages/react-native-css-interop/package.json
I setup v4 on a personal project and could not get my CI to successfully pass because he could not find this file `react-native-css-interop-env/types`:
+ a small tweak to the main package test app script
=> V4: Fix to missing react-native-css-interop-env/types reference + another small tweak

apps/website/docs/getting-started/expo-router.mdx, apps/website/docs/getting-started/metro.mdx, apps/website/src/pages/v4/troubleshooting.mdx
When checking the [documentation](https://www.nativewind.dev/v4/getting-started/metro) to configure my test project using nativewind V4, I noticed that in the TailwindCSS configuration section, it is showing to add the **preset** and not **presets**, according to the [tailwindcss documentation](https://tailwindcss.com/docs/presets)
=> fix doc V4 - tailwindcss config presets 

apps/website/docs/getting-started/_install.mdx
Running the guide to install NativeWind v4 in my React Native project, I encountered an issue.
This was right after installing the dependencies. I noticed that it's necessary to run a pod install to install the Reanimated pod, as mentioned in the docs: https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/getting-started/#ios.
So I propose this change in the React Native guide, including the instruction to run pod install right after installing the dependencies.
=> Add pod-install instruction

apps/website/docs/getting-started/nextjs.mdx, apps/website/docs/getting-started/react-native.mdx, apps/website/versioned_docs/version-v2/guides/universal-system.md, apps/website/versioned_docs/version-v2/quick-starts/nextjs.md
This labeling aligns a bit more closely with how things are named in the React docs https://react.dev/learn/start-a-new-react-project where the recommended flow is a framework and the alternative is no framework.
=> change vanilla label to "framework-less"

apps/website/docs/getting-started/_install.mdx, apps/website/docs/getting-started/_tailwind.mdx, apps/website/docs/getting-started/expo-router.mdx, apps/website/docs/getting-started/react-native.mdx
- The diff blocks make it harder to copy/paste as you need to go back and remove the `+` and `-` characters. In most cases there is no file to diff, e.g. `tailwind.config.js` file won't exist in a React Native project until I add this library. In other cases it seems like users will be familiar enough with the modifications they added manually to diff themselves.
- Using dev deps for `tailwindcss`  is not necessary and causes issues with eas build where production installs will skip dev deps. I've moved this to the standard dependencies installation.
- `your-css-file.css` is needlessly abstract. Most users are probably just going to want the standard tailwind setup, which uses `global.css`. This allows for more copy/paste.
- Added SDK 50 babel instructions and align with the upstream …
=> update installation docs

apps/website/docs/getting-started/react-native.mdx
Getting Started - React Native-Modify your metro.config.js
npm start Error
error Cannot read properties of undefined (reading 'sourceExts').
=> fix(docs):"npm start" error

apps/website/docs/quick-starts/expo.md
At the moment when following the [Expo quick start guide](https://www.nativewind.dev/quick-starts/expo) users might stumble upon an error due to an incompatible `tailwindcss` version.
This issue relates to this issue #498 where users receive this error
```
Error: Use process(css).then(cb) to work with async plugins
```
Edit documentation by prompting the user to install the latest `tailwindcss` compatible version v3.3.2 and adding a warning
=> docs: update expo quick start with compatible tailwindcss version

.changeset/soft-poets-cheat.md, packages/react-native-css-interop/src/__tests__/sanity-checks.test.tsx, packages/react-native-css-interop/src/runtime/native/api.ts, packages/react-native-css-interop/src/runtime/web/api.ts
fixes #650 for components using tailwind-merge which returns an empty string instead on undefined
=> [V4] Ignore className if empty string is provided

apps/website/docs/customization/colors.md, apps/website/docs/customization/configuration.md, apps/website/docs/customization/theme.md
Found some grammatical issues and typos while going through some of the pages in the docs. This PR is an attempt to fix them.
Tested them locally by running `yarn build`, `cd build/`, and then `npm run server`.
=> [docs] Fix typos

.changeset/rich-hairs-lie.md, packages/nativewind/src/metro/tailwind/v3/index.ts
This check was introduced in version 4.1 and now incorrectly throws an error even though 'nativewind/preset' is present in the resolved configuration.
This PR resolves the issue by flattening the presets to detect nativewind preset under nested configuration.
=> Detect nativewind/preset recursively

apps/website/docs/getting-started/expo-router.mdx
typescript was throwing error on how Slot wasn't exported from expo router in previous import in latest create-expo-app project
=> fixed Slot import

apps/website/docusaurus.config.js
Hey, I noticed it's hard to find the Discord so I added a link to the Discord to the header and footer. Let me know what you think about this change.
If you don't like that now there is so much text in the header we can also change the discord and github text to logos
=> feat: added discord links to the website

.changeset/angry-swans-ring.md, packages/react-native-css-interop/src/__tests__/custom-components.test.tsx, packages/react-native-css-interop/src/__tests__/refs.test.tsx, packages/react-native-css-interop/src/runtime/config.ts, packages/react-native-css-interop/src/runtime/native/api.ts, packages/react-native-css-interop/src/runtime/native/native-interop.ts, packages/react-native-css-interop/src/runtime/native/resolve-value.ts, packages/react-native-css-interop/src/runtime/native/utils.ts, packages/react-native-css-interop/src/runtime/web/api.ts, packages/react-native-css-interop/src/types.ts, packages/react-native-css-interop/src/utils/test/index.tsx
Allow dot notation for the `target` prop in cssInterop
```
cssInterop(BottomSheet.Navigator, {
backgroundClassName: "screenOptions.backgroundStyle"
})
```
=> allow dot notation for cssInterop config targetting

.changeset/weak-mice-peel.md, packages/react-native-css-interop/src/__tests__/debugging.test.tsx, packages/react-native-css-interop/src/__tests__/grouping.test.tsx, packages/react-native-css-interop/src/__tests__/transitions.test.tsx, packages/react-native-css-interop/src/runtime/native/native-interop.ts, packages/react-native-css-interop/src/runtime/native/types.ts
Allow `<Text className="active:transition-colors active:text-red-500" />` to work.
Previously you would need to specify a non-active `color` & `transition`. Now it works like this:
- Initial render
- No styles are rendered
- Component is tagged as animated
- onPressIn
- Styles are applied.
- Text will transition from black (the default text color) to red
- onPressOut
- Styles are applied
- Default transition is applied (`property: []`).
- Cleanup step resets the SharedValues to their default value
- Text changes back to black (the default text color) with no transition (the transition was only applied on `active`)
> [!NOTE]  
> You still need to ensure that the component is animated during the initial render (`active:transition-{n}`) is fine. These classes still cannot be dynamically …
=> Allow transition to be specified in an optional style

.changeset/small-colts-marry.md, packages/react-native-css-interop/src/runtime/native/native-interop.ts
After testing on tvos, everything works fine except `active:` classes. There are some small things we can do in the future (e.g `tv:` modifier) but this is all that is needed for now
Related https://github.com/douglowder/NativeWindTV/pull/1
=> support tvos

.changeset/six-plums-stare.md, packages/react-native-css-interop/src/runtime/native/styles.ts
First of all, thank you for your great work!
The current implementation of styleWarnings prevents recurring styles - which have previously set an error message - from being returned.
An example for this is gap-x-[n]. This includes following warning: `{"property": "-webkit-column-gap", "type": "IncompatibleNativeProperty"}, {"property": "-moz-column-gap", "type": "IncompatibleNativeProperty"}`.
As a warning is now set in the first run of getStyle, the style is no longer returned if the className exists a second time. 
Example: 
```
<View className="w-full gap-y-3">
<View className="flex-row items-stretch gap-x-3">
<View className="h-[50px] flex-1 bg-black" />
<View className="h-[50px] flex-1 bg-black" />
</View>
<View className="flex-row items-stretch gap-x-3">
<View className="h-[50px] …
```
=> ensure that styles that have a warning are returned

.changeset/quick-crabs-jam.md, packages/react-native-css-interop/src/__tests__/grouping.test.tsx, packages/react-native-css-interop/src/__tests__/remap-props.test.tsx, packages/react-native-css-interop/src/__tests__/transitions.test.tsx, packages/react-native-css-interop/src/css-to-rn/index.ts, packages/react-native-css-interop/src/runtime/native/native-interop.ts
Removes unused `specificity` values from the generated styles
=> reduce size of style output by reducing specificity size

packages/nativewind/src/test.tsx, packages/react-native-css-interop/src/test/index.tsx
Allow for `renderCurrentTest.debug()` / `render.debug()` to most easily toggle debugging output in tests.
=> improve UX for debugging test output

.changeset/metal-eyes-cover.md, packages/react-native-css-interop/src/runtime/native/native-interop.ts
It would probably be a better separation of concerns, and more maintainable and configurable, to revert this change. Instead, I propose to modify RNTV to send the expected `onPressIn` and `onPressOut` methods when controls are selected.
For example, the TV repo could add a new prop to `Pressable` and `Touchable` to configure the amount of time `active` is true when the TV remote selects a control.
Example of what the RNTV change might look like: https://github.com/douglowder/NativeWindTV/blob/doug/nativewind-v4/patches/react-native%2B0.74.5-0.patch
=> Revert "support tvos (#1061)"

.changeset/large-eels-work.md, package-lock.json, packages/nativewind/package.json, packages/nativewind/src/metro/index.ts, packages/nativewind/src/metro/tailwind/index.ts, packages/nativewind/src/metro/tailwind/v3/index.ts, packages/react-native-css-interop/package.json, packages/react-native-css-interop/src/css-to-rn/index.ts, packages/react-native-css-interop/src/metro/index.ts, packages/react-native-css-interop/src/types.ts
Add debug output when `DEBUG=nativewind`  is set.
```
➜  expo-router git:(main) ✗ DEBUG=nativewind npx expo start        
Starting project at /Users/mark/Projects/nativewind/examples/expo-router
nativewind input: /Users/mark/Projects/nativewind/examples/expo-router/global.css +0ms
nativewind important: undefined +26ms
nativewind checking TypeScript setup +0ms
nativewind withCssInterop: successfully called +82ms
nativewind platforms: ios,android,web,native +0ms
nativewind prodOutputDir: /Users/mark/Projects/nativewind/packages/react-native-css-interop/.cache +0ms
Starting Metro Bundler
nativewind enhanceMiddleware successfully called +229ms
› Metro waiting on exp://192.168.1.4:8081
› Scan the QR code above with Expo Go (Android) or the Camera app (iOS)
› Web is waiting on …
```
=> add `DEBUG=nativewind` for Metro debugging

.changeset/pink-students-kneel.md, packages/nativewind/src/metro/index.ts, packages/react-native-css-interop/src/metro/index.ts, packages/react-native-css-interop/src/metro/transformer.ts
Some projects generate an huge amount of styles which lead to large generated JS files.
When NativeWind updates a style, this entire file is passed to Metro and subsequently transformed via Babel. Locally using ~14000 styles a Fast Refresh update may take ~8 seconds.
This PR adds a custom transform that skips transforming the large JS bundle. This reduces the Fast Refresh time to ~2.5s.
For reference, Metro takes ~700ms to complete a standard Fast Refresh (from sending the file changed event to appearing on device). So ~2.5s is still not ideal, but there are other known issues that will be fixed in other PRs. 
Numbers are reference only. Just recorded values on my machine while testing.
cc: @Viraj-10
=> Avoid transforming styles JS file

packages/react-native-css-interop/src/__tests__/babel-plugin.test.ts, packages/react-native-css-interop/src/babel-plugin.ts
Analytics libraries like datadog patch `React.createElement` to override onPress prop for tracking. [Here](https://github.com/DataDog/dd-sdk-reactnative/blob/5b8a26c61afc7c454c180fdc44ac23168733c682/packages/core/src/rum/instrumentation/interactionTracking/DdRumUserInteractionTracking.tsx#L31)
Although, not a huge fan of the approach taken here by the datadog library as alternate solutions exist. But I think `react-native-css-interop` should support such a usecase as the original `React.createElement` doesn't prevent patching.
RN CSS interop uses named import `createInteropElement` to replace `createElement`, this prevents patching, as babel transpiles such imports to read-only. The approach taken in this PR is to use namespace imports. e.g. `createElement` will become …
=> fix: allow patching of react.createElement

packages/nativewind/src/metro/tailwind/v3/index.ts
XCode isn't always configured to run NodeJS. Since we are already in a NodeJS process, we can spawn the Tailwind CLI using the same binary.
=> Spawn TailwindCLI using the current NodeJS binary

.changeset/poor-guests-hide.md, packages/nativewind/src/__tests__/unofficial-plugins.test.ios.tsx, packages/react-native-css-interop/src/__tests__/shorthand.test.tsx, packages/react-native-css-interop/src/css-to-rn/parseDeclaration.ts, packages/react-native-css-interop/src/runtime/native/native-interop.ts, packages/react-native-css-interop/src/runtime/native/resolve-value.ts, packages/react-native-css-interop/src/runtime/native/resolvers/shared.ts, packages/react-native-css-interop/src/runtime/native/resolvers/shorthand.ts, packages/react-native-css-interop/src/runtime/native/resolvers/text-shadow.ts, packages/react-native-css-interop/src/runtime/native/types.ts, packages/react-native-css-interop/src/shared.ts, packages/react-native-css-interop/src/test/index.tsx
Add support for runtime shorthand parsing. This allows people to use CSS variables to for multiple shorthand values.
PR only adds support for `text-shadow`, as each shorthand needs its syntax added.
=> Add runtime shorthand parsing

packages/nativewind/src/tailwind/index.ts
With this PR, editors like VS Code will be aware of the features in native implementations, such as `p-safe`.
=> Load `native` presets to enhance auto-completion

apps/website/docs/tailwind/new-concepts/safe-area-insets.mdx
The code examples in the comments were missing indentation, e.g.
```
{
marginTop: env(safe-area-inset-top)
}
```
would be rendered as
```
{
marginTop: env(safe-area-inset-top)
}
```
The trimming seems to be caused by https://github.com/syntax-tree/mdast-util-mdx-jsx/pull/15
Instead of waiting for an upstream fix this commit refactors the examples to remove the indentation and use CSS properties instead of JS objects.
=> Fix website code examples for safe area insets

apps/website/docs/tailwind/layout/box-sizing.mdx
Correct typo in box sizing class name `box-context` -> `box-content`
https://tailwindcss.com/docs/box-sizing
=> docs: fix box-content typo

packages/react-native-css-interop/package.json
Users are running into build issues with EAS due to a discrepancy in `lightningcss` versions between `react-native-css-interop` and `@expo/metro-config`. Likely due to a recent change on Expo's end. This downgrades our version from `^1.27.0` to `~1.19.0` to match what Expo has.
=> Downgrade lightningcss to match @expo/metro-config

apps/website/docs/tailwind/backgrounds/background-color.mdx
The config key was incorrect, i.e., it was corePlugin instead of corePlugins
=> typo fix for tailwind.config.js file

README.md
This PR fixes a broken link in the README.md under the Installation section.
**What was fixed**
Old link: https://www.nativewind.dev/getting-started/installation (broken)
New link: https://www.nativewind.dev/docs/getting-started/installation (correct path)
=> Fix broken or outdated documentation link for installation guide

packages/react-native-css-interop/babel.js, packages/react-native-css-interop/src/runtime/native/render-component.tsx
These changes are needed to support React Native 0.81 and Reanimated 4 with the current version of Nativewind (v4).
See demo app at https://github.com/react-native-tvos/NativewindMultiplatform/tree/sdk-54-beta .
Reanimated 4 also requires a fix for this to work, see https://github.com/software-mansion/react-native-reanimated/pull/8099 .
=> [css-interop] Fixes for RN 0.81 and reanimated 4
