- src/styled-component.tsx
This fixes https://github.com/marklawlor/tailwindcss-react-native/issues/68
> [Fix] Styled components unmount/mount every render

- src/classname-to-inline-style.ts
fixes #71, switched to a more compatible regex.
> fix: remove regex negative lookbehind for safari compatibility

- packages/nativewind/src/postcss/fs-writer.ts
Fix _NativeWindStyleSheet is undefined in nativewind output js file
> fix _NativeWindStyleSheet undefined in nativewind output js file

- apps/website/docusaurus.config.js
Congrats on the release @marklawlor! Thrilled to see it 😀
> chore(docs): remove pre-release announcement

- .changeset/olive-pets-grow.md
- packages/nativewind/__tests__/snapshots/__snapshots__/props.tsx.snap
- packages/nativewind/src/styled/with-styled-children.ts
> fix: filter out null values when rendering styled children

- apps/website/docs/guides/postcss.md
This PR adjusts some grammar in the PostCSS docs.
> docs: fix grammar

- apps/website/docs/quick-starts/expo.md
See: https://github.com/marklawlor/nativewind/issues/281#issuecomment-1285548446
> cites example project for expo web

- apps/website/docs/quick-starts/solito.md
adding link to the solito nativewind starter as well as a the npx script to install it on docs
> add solito starter information to solito.md

- packages/react-native-css-interop/src/css-to-rn/parseDeclaration.ts
Was trying to use `gap-x-1` in my code and it wasn't working. This fixes it
> Fix column-gap issue `gap-x-*`

- packages/react-native-css-interop/src/runtime/web/variables.ts
we can get type check for vars to add themes.
#707
> add type check for vars

- packages/nativewind/src/metro/transformer.ts
> Escape windows path during metro transform

- apps/website/docs/guides/goals.mdx
- apps/website/versioned_docs/version-v2/guides/goals.mdx
- In reading the docs, I noticed this was a typo, so this PR is a fix for that
> fix/typo fix for 'Align with Tailwind CSS' section of the docs

- apps/website/docs/core-concepts/quirks.md
- apps/website/package.json
- apps/website/sidebars.js
As pointed out in https://github.com/nativewind/nativewind/discussions/1016 this section was removed.
I think this was important so I'm adding it back
> [docs]: Re-add quirks section

- package-lock.json
- packages/nativewind/package.json
- packages/nativewind/src/__tests__/unofficial-plugins.test.ios.tsx
- packages/nativewind/src/test.tsx
Related #1024
This plugin is interesting as it allows you to easily setup multiple themes. Its one of the most popular plugins on npm
> add test for tw-colors

- .changeset/chatty-doors-push.md
- packages/react-native-css-interop/src/metro/index.ts
> fix bundling for web

- .changeset/friendly-spiders-love.md
- packages/react-native-css-interop/src/__tests__/debugging.test.tsx
- packages/react-native-css-interop/src/__tests__/variables.test.tsx
- packages/react-native-css-interop/src/runtime/native/appearance-observables.ts
- packages/react-native-css-interop/src/runtime/native/native-interop.ts
- packages/react-native-css-interop/src/runtime/native/styles.ts
> fix variable and container cascade

- .changeset/gold-actors-add.md
- packages/nativewind/src/__tests__/safe-area.test.ios.tsx
- packages/nativewind/src/tailwind/safe-area.ts
- packages/nativewind/src/test.tsx
- packages/react-native-css-interop/src/__tests__/grouping.test.tsx
- packages/react-native-css-interop/src/css-to-rn/parseDeclaration.ts
Adds support to have logical parenthesis in calc functions.
```
calc(a - (b + c))
```
To test this, I've updated the `safe-area` classes to the latest plugin version.
> Support parenthesis in calc functions

- .changeset/swift-buckets-clap.md
- packages/react-native-css-interop/src/__tests__/react-native-components.test.tsx
- packages/react-native-css-interop/src/runtime/native/native-interop.ts
> fix some styles not being applied when targetting non-style props

- .changeset/weak-mice-peel.md
- packages/react-native-css-interop/src/__tests__/debugging.test.tsx
- packages/react-native-css-interop/src/__tests__/grouping.test.tsx
- packages/react-native-css-interop/src/__tests__/transitions.test.tsx
- packages/react-native-css-interop/src/runtime/native/native-interop.ts
- packages/react-native-css-interop/src/runtime/native/types.ts
Revert a revert that added a test allowing the test suite to pass.
> Attempt 3: Bump to v4.1.10

- .changeset/pink-colts-shave.md
- packages/react-native-css-interop/src/__tests__/variables.test.tsx
- packages/react-native-css-interop/src/runtime/native/native-interop.ts
> Fix variables not being inherited

- .changeset/rich-beans-rest.md
- packages/nativewind/src/__tests__/dark-mode.ios.tsx
- packages/react-native-css-interop/src/__tests__/selectors.test.tsx
- packages/react-native-css-interop/src/css-to-rn/normalize-selectors.ts
> Fix parsing of :is(.dark *)

- .changeset/long-items-camp.md
- apps/website/docs/tailwind/new-concepts/safe-area-insets.mdx
- packages/nativewind/src/__tests__/safe-area.test.ios.tsx
- packages/react-native-css-interop/src/runtime/components.ts
- packages/react-native-css-interop/src/runtime/native/api.ts
- packages/react-native-css-interop/src/runtime/native/styles.ts
- packages/react-native-css-interop/src/runtime/third-party-libs/react-native-safe-area-context.tsx
- packages/react-native-css-interop/src/runtime/wrap-jsx.ts
Remake of https://github.com/nativewind/nativewind/pull/1062
Fixed the infinite loop issue
> Easier SafeArea classes

- packages/react-native-css-interop/src/__tests__/variables.test.tsx
- packages/react-native-css-interop/src/css-to-rn/index.ts
- packages/react-native-css-interop/src/types.ts
Reduce the output size by removing any unused variables
> Remove unused variables

- .changeset/two-pants-jump.md
- packages/nativewind/src/__tests__/transition-animations.tsx
- packages/react-native-css-interop/src/css-to-rn/index.ts
- packages/react-native-css-interop/src/runtime/native/resolve-value.ts
Animations like `animate-pulse` were rendering with an incorrect 100% frame
> Ensure animation 100% frame is calculated correctly

- apps/website/versioned_docs/version-v2/quick-starts/solito.md
Sorry, my OCD prevents me from not making a PR for this
> fix: Docs typo in solito.md

- apps/website/versioned_docs/version-v2/guides/tailwindcss-react-native.md
english in this sentance was bit wrong, changed it
> Fixing a sentence in the doc

- package-lock.json
- packages/react-native-css-interop/package.json
> Restrict lightningcss to 1.27.x
